### ISSUE TITLE
Craft Commerce 5 compatibility 

### ISSUE THREAD

**Issue by mgambella** [digital-pros/commerce-authorize#47] opened 2024-04-22 23:06 UTC
With Craft Commerce 5 released, I wanted to check if this is going to be updated for the new version.

**Comment by benlobach** [comment] 2024-05-30 16:02
Closing this ticket as it's a duplicate of #46, and we'll update the status there as we work toward Craft Commerce 5 compatibility.

**Closed by benlobach** 2024-05-30 16:02 UTC

**Comment by benlobach** [comment] 2024-06-07 16:42
@mgambella - Version 5 has been released, let us know if you run into any hiccups!
